2017/04/22 10:56:06 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in /srv/http/veber/framework/db/CDbConnection.php:399
Stack trace:
#0 /srv/http/veber/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /srv/http/veber/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /srv/http/veber/framework/base/CModule.php(394): CDbConnection->init()
#3 /srv/http/veber/framework/base/CApplication.php(459): CModule->getComponent('db')
#4 /srv/http/veber/framework/db/ar/CActiveRecord.php(637): CApplication->getDb()
#5 /srv/http/veber/framework/db/ar/CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 /srv/http/veber/framework/db/ar/CActiveRecord.php(1474): CActiveRecord->getCommandBuilder()
#7 /srv/http/veber/www/protected/controllers/SiteController.php(34): CActiveRecord->findAll(Object(CDbCriteria))
#8 /srv/http/veber/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#9 /srv/http/veber/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /srv/http/veber/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /srv/http/veber/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /srv/http/veber/framework/web/CWebApplication.php(282): CController->run('')
#13 /srv/http/veber/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /srv/http/veber/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /srv/http/veber/www/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
